var spawn = require('child_process').spawn
  , testHelpers = require('./test/helpers')

desc('prepare & run api tests')
task('test', [ 'test:prepare', 'test:fixtures', 'test:api'], function() {
  process.exit()
})

namespace('test', function() {
  desc('prepares database')
  task('prepare', [], function() {
    testHelpers.dropDatabase(complete)
  }, true)

  desc('applies test fixtures')
  task('fixtures', [], function() {
    testHelpers.applyFixtures(complete)
  }, true)

  desc('run tests with vows')
  task('api', [ 'test:prepare', 'test:fixtures' ], function() {
    var vows = spawn('vows', [ '--spec', 'test/app.test.js' ])

    vows.stdout.on('data', function(chunk) {
      process.stdout.write(chunk)
    })
    vows.stderr.on('data', function(chunk) {
      process.stderr.write(chunk)
    })
    vows.on('exit', function(code) {
      complete()
    })
  }, true)
})
